# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/ui_design/main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_map = QtWidgets.QLabel(self.centralwidget)
        self.label_map.setGeometry(QtCore.QRect(140, 50, 500, 500))
        self.label_map.setObjectName("label_map")
        self.type_map = QtWidgets.QComboBox(self.centralwidget)
        self.type_map.setGeometry(QtCore.QRect(10, 20, 69, 22))
        self.type_map.setObjectName("type_map")
        self.type_map.addItem("")
        self.type_map.addItem("")
        self.type_map.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_map.setText(_translate("MainWindow", "TextLabel"))
        self.type_map.setItemText(0, _translate("MainWindow", "Схема"))
        self.type_map.setItemText(1, _translate("MainWindow", "Спутник"))
        self.type_map.setItemText(2, _translate("MainWindow", "Гибрид"))
